spring:
  profiles.active: local

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      max-lifetime: 56000
      connection-timeout: 2000
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    defer-datasource-initialization: true
    generate-ddl: true
  logging:
    level:
      org.hibernate.sql: debug
  aws:
    region: ap-northeast-2
    s3:
      raw-bucketName: tiny-human-local
      thumbnail-bucketName: tiny-human-thumbnail-local
  jwt:
    issuer: abc@tinyhuman.com
    secretkey: ${JWT_SECRET_KEY}


# docker run -p 8080:8080 -e SPRING_DATASOURCE_URL -e SPRING_DATASOURCE_USERNAME -e SPRING_DATASOURCE_PASSWORD -e SPRING_JWT_SECRETKEY -e SPRING_AWS_ACCESSKEYID -e SPRING_AWS_SECRETACCESSKEY tiny-human-api .