spring:
  profiles.active: local
---
spring:
  config:
    activate:
      on-profile: local
  flyway:
    enabled: false
  datasource:
    url: jdbc:mariadb://localhost:13306/tinyhuman_db?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: password
    hikari:
      max-lifetime: 56000
      connection-timeout: 2000
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 300MB
aws:
  s3:
    bucketName: tiny-human-dev
    path:
      profile: images/babyId/profile/
      diary: images/babyId/diary/
      album: images/babyId/album/
jwt:
  issuer: abc@tinyhuman.com
  secret_key: gqe213bfl3quh2
logging:
  level:
    org.hibernate.sql: debug