spring:
  profiles.active: local
---
spring:
  config:
    activate:
      on-profile: local
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_schema: tiny-human
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 300MB
aws:
  s3:
    raw-bucketName: tiny-human-dev
    thumbnail-bucketName: tiny-human-thumbnail-dev
jwt:
  issuer: abc@tinyhuman.com
  secret_key: gqe213bfl3quh2
logging:
  level:
    org.hibernate.sql: debug