package com.tinyhuman.tinyhumanapi.baby.mock;

import com.tinyhuman.tinyhumanapi.baby.domain.Baby;
import com.tinyhuman.tinyhumanapi.baby.enums.Gender;
import com.tinyhuman.tinyhumanapi.baby.service.port.BabyRepository;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

public class FakeBabyRepository implements BabyRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0L);

    private final List<Baby> data = new ArrayList<>();

    @Override
    public Baby save(Baby baby) {
        if (baby.id() == null || baby.id() == 0) {
            Baby newBaby = Baby.builder()
                    .id(autoGeneratedId.incrementAndGet())
                    .name("김가나")
                    .gender(Gender.MALE)
                    .nickName("초코")
                    .timeOfBirth(10)
                    .dayOfBirth(LocalDate.of(2022, 9, 20))
                    .timeOfBirth(20)
                    .profileImgUrl(baby.profileImgUrl())
                    .build();
            data.add(baby);
            return newBaby;
        } else {
            data.removeIf(b -> Objects.equals(b.id(), baby.id()));
            data.add(baby);
            return baby;
        }
    }

    @Override
    public Optional<Baby> findById(Long id) {
        return data.stream()
                .filter(baby -> baby.id().equals(id))
                .findAny();
    }

    @Override
    public void delete(Long id) {

    }

}
