package com.tinyhuman.tinyhumanapi.diary.mock;

import com.tinyhuman.tinyhumanapi.diary.domain.Diary;
import com.tinyhuman.tinyhumanapi.diary.domain.Picture;
import com.tinyhuman.tinyhumanapi.diary.service.port.PictureRepository;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;

public class FakePictureRepository implements PictureRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0L);

    private final List<Picture> data = new ArrayList<>();
    @Override
    public List<Picture> saveAll(List<Picture> pictures, Diary savedDiary) {

        for (Picture picture : pictures) {

            Picture newPicture = picture.builder()
                    .id(autoGeneratedId.incrementAndGet())
                    .isMainPicture(picture.isMainPicture())
                    .contentType(picture.contentType())
                    .originalS3Url(picture.originalS3Url())
                    .diaryId(picture.diaryId())
                    .build();

            data.removeIf(p -> Objects.equals(p.id(), newPicture.id()));
            data.add(newPicture);
        }

        return pictures;
    }
}
