package com.tinyhuman.tinyhumanapi.diary.mock;

import com.tinyhuman.tinyhumanapi.diary.domain.Diary;
import com.tinyhuman.tinyhumanapi.diary.domain.Sentence;
import com.tinyhuman.tinyhumanapi.diary.service.port.SentenceRepository;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;

public class FakeSentenceRepository implements SentenceRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0L);

    private final List<Sentence> data = new ArrayList<>();
    @Override
    public List<Sentence> saveAll(List<Sentence> sentences, Diary savedDiary) {

        for (Sentence sentence : sentences) {
            Sentence newSentence = Sentence.builder()
                    .id(autoGeneratedId.incrementAndGet())
                    .sentence(sentence.sentence())
                    .diaryId(sentence.diaryId())
                    .build();
            

            data.removeIf(s -> Objects.equals(s.id(), newSentence.id()));
            data.add(newSentence);
        }
        return sentences;
    }
}
