INSERT INTO users (is_deleted, status, created_at, id, last_login_at, updated_at, created_by, email, name, password, updated_by) VALUES (false, 'ACTIVE', '2023-08-17 15:27:48.051351', 1, null, '2023-08-17 15:27:48.051351', null, 'test@gmail.com', '신', '1234', null);

INSERT INTO babies (day_of_birth, is_deleted, time_of_birth, created_at, id, updated_at, user_id, created_by, gender, name, nick_name, profile_img_key_name, updated_by) VALUES ('2022-09-27', false, 14, '2023-08-17 15:27:50.345741', 1, '2023-08-17 15:27:50.345741', null, null, 'FEMALE', '신지', '리카', 'https://tiny-human-dev.s3.ap-northeast-2.amazonaws.com/images/1/profile/DSCF7306.JPG', null);

INSERT INTO user_baby_relations (is_deleted, baby_id, created_at, updated_at, user_id, created_by, relation, role, updated_by) VALUES (false, 1, '2023-08-17 15:27:50.382922', '2023-08-17 15:27:50.382922', 1, null, 'FATHER', 'ADMIN', null);

INSERT INTO albums (gps_lat, gps_lon, is_deleted, baby_id, created_at, id, original_created_at, updated_at, content_type, created_by, key_name, updated_by) VALUES (null, null, false, 1, null, 1, null, null, 'PHOTO', null, 'keyName1', null);
INSERT INTO albums (gps_lat, gps_lon, is_deleted, baby_id, created_at, id, original_created_at, updated_at, content_type, created_by, key_name, updated_by) VALUES (null, null, false, 1, null, 2, null, null, null, null, 'keyName2', null);
INSERT INTO albums (gps_lat, gps_lon, is_deleted, baby_id, created_at, id, original_created_at, updated_at, content_type, created_by, key_name, updated_by) VALUES (null, null, false, 1, null, 3, null, null, null, null, 'keyName3', null);
INSERT INTO albums (gps_lat, gps_lon, is_deleted, baby_id, created_at, id, original_created_at, updated_at, content_type, created_by, key_name, updated_by) VALUES (null, null, false, 1, null, 4, null, null, null, null, 'keyName4', null);
INSERT INTO albums (gps_lat, gps_lon, is_deleted, baby_id, created_at, id, original_created_at, updated_at, content_type, created_by, key_name, updated_by) VALUES (null, null, false, 1, null, 5, null, null, null, null, 'keyName5', null);
INSERT INTO albums (gps_lat, gps_lon, is_deleted, baby_id, created_at, id, original_created_at, updated_at, content_type, created_by, key_name, updated_by) VALUES (null, null, false, 1, null, 6, null, null, null, null, 'keyName6', null);
INSERT INTO albums (gps_lat, gps_lon, is_deleted, baby_id, created_at, id, original_created_at, updated_at, content_type, created_by, key_name, updated_by) VALUES (null, null, false, 1, null, 7, null, null, null, null, 'keyName7', null);
INSERT INTO albums (gps_lat, gps_lon, is_deleted, baby_id, created_at, id, original_created_at, updated_at, content_type, created_by, key_name, updated_by) VALUES (null, null, false, 1, null, 8, null, null, null, null, 'keyName8', null);
INSERT INTO albums (gps_lat, gps_lon, is_deleted, baby_id, created_at, id, original_created_at, updated_at, content_type, created_by, key_name, updated_by) VALUES (null, null, false, 1, null, 9, null, null, null, null, 'keyName9', null);
INSERT INTO albums (gps_lat, gps_lon, is_deleted, baby_id, created_at, id, original_created_at, updated_at, content_type, created_by, key_name, updated_by) VALUES (null, null, false, 1, null, 10, null, null, null, null, 'keyName10', null);
INSERT INTO albums (gps_lat, gps_lon, is_deleted, baby_id, created_at, id, original_created_at, updated_at, content_type, created_by, key_name, updated_by) VALUES (null, null, false, 1, null, 11, null, null, 'PHOTO', null, 'keyName11', null);
INSERT INTO albums (gps_lat, gps_lon, is_deleted, baby_id, created_at, id, original_created_at, updated_at, content_type, created_by, key_name, updated_by) VALUES (null, null, false, 1, null, 12, null, null, null, null, 'keyName12', null);
INSERT INTO albums (gps_lat, gps_lon, is_deleted, baby_id, created_at, id, original_created_at, updated_at, content_type, created_by, key_name, updated_by) VALUES (null, null, false, 1, null, 13, null, null, null, null, 'keyName13', null);
INSERT INTO albums (gps_lat, gps_lon, is_deleted, baby_id, created_at, id, original_created_at, updated_at, content_type, created_by, key_name, updated_by) VALUES (null, null, false, 1, null, 14, null, null, null, null, 'keyName14', null);
INSERT INTO albums (gps_lat, gps_lon, is_deleted, baby_id, created_at, id, original_created_at, updated_at, content_type, created_by, key_name, updated_by) VALUES (null, null, false, 1, null, 15, null, null, null, null, 'keyName15', null);
INSERT INTO albums (gps_lat, gps_lon, is_deleted, baby_id, created_at, id, original_created_at, updated_at, content_type, created_by, key_name, updated_by) VALUES (null, null, false, 1, null, 16, null, null, null, null, 'keyName16', null);
INSERT INTO albums (gps_lat, gps_lon, is_deleted, baby_id, created_at, id, original_created_at, updated_at, content_type, created_by, key_name, updated_by) VALUES (null, null, false, 1, null, 17, null, null, null, null, 'keyName17', null);
INSERT INTO albums (gps_lat, gps_lon, is_deleted, baby_id, created_at, id, original_created_at, updated_at, content_type, created_by, key_name, updated_by) VALUES (null, null, false, 1, null, 18, null, null, null, null, 'keyName18', null);
INSERT INTO albums (gps_lat, gps_lon, is_deleted, baby_id, created_at, id, original_created_at, updated_at, content_type, created_by, key_name, updated_by) VALUES (null, null, false, 1, null, 19, null, null, null, null, 'keyName19', null);
INSERT INTO albums (gps_lat, gps_lon, is_deleted, baby_id, created_at, id, original_created_at, updated_at, content_type, created_by, key_name, updated_by) VALUES (null, null, false, 1, null, 20, null, null, null, null, 'keyName20', null);
INSERT INTO albums (gps_lat, gps_lon, is_deleted, baby_id, created_at, id, original_created_at, updated_at, content_type, created_by, key_name, updated_by) VALUES (null, null, false, 1, null, 21, null, null, 'PHOTO', null, 'keyName21', null);
INSERT INTO albums (gps_lat, gps_lon, is_deleted, baby_id, created_at, id, original_created_at, updated_at, content_type, created_by, key_name, updated_by) VALUES (null, null, false, 1, null, 22, null, null, null, null, 'keyName22', null);
INSERT INTO albums (gps_lat, gps_lon, is_deleted, baby_id, created_at, id, original_created_at, updated_at, content_type, created_by, key_name, updated_by) VALUES (null, null, false, 1, null, 23, null, null, null, null, 'keyName23', null);
INSERT INTO albums (gps_lat, gps_lon, is_deleted, baby_id, created_at, id, original_created_at, updated_at, content_type, created_by, key_name, updated_by) VALUES (null, null, false, 1, null, 24, null, null, null, null, 'keyName24', null);
INSERT INTO albums (gps_lat, gps_lon, is_deleted, baby_id, created_at, id, original_created_at, updated_at, content_type, created_by, key_name, updated_by) VALUES (null, null, false, 1, null, 25, null, null, null, null, 'keyName25', null);
INSERT INTO albums (gps_lat, gps_lon, is_deleted, baby_id, created_at, id, original_created_at, updated_at, content_type, created_by, key_name, updated_by) VALUES (null, null, false, 1, null, 26, null, null, null, null, 'keyName26', null);
INSERT INTO albums (gps_lat, gps_lon, is_deleted, baby_id, created_at, id, original_created_at, updated_at, content_type, created_by, key_name, updated_by) VALUES (null, null, false, 1, null, 27, null, null, null, null, 'keyName27', null);
INSERT INTO albums (gps_lat, gps_lon, is_deleted, baby_id, created_at, id, original_created_at, updated_at, content_type, created_by, key_name, updated_by) VALUES (null, null, false, 1, null, 28, null, null, null, null, 'keyName28', null);
INSERT INTO albums (gps_lat, gps_lon, is_deleted, baby_id, created_at, id, original_created_at, updated_at, content_type, created_by, key_name, updated_by) VALUES (null, null, false, 1, null, 29, null, null, null, null, 'keyName29', null);
INSERT INTO albums (gps_lat, gps_lon, is_deleted, baby_id, created_at, id, original_created_at, updated_at, content_type, created_by, key_name, updated_by) VALUES (null, null, false, 1, null, 30, null, null, null, null, 'keyName30', null);